### ISSUE TITLE
Generated specification does not work well with Swagger Codegen

### ISSUE THREAD

**Issue by EFanZh** [rnduldulaojr/tornado-swirl#34]
The server URL in the generated specifications has a trailing “/” in it:

https://github.com/rduldulao/tornado-swirl/blob/dea6f214c0f295820ed0966a769be9a9cdca9e5f/tornado_swirl/views.py#L87-L90

And Swagger Codegen generates API URL by concatenating server URL with resource path:

https://github.com/swagger-api/swagger-codegen-generators/blob/74593eec7c73d5deb836bcc17171c259e4deda87/src/main/resources/handlebars/python/api_client.mustache#L142-L143

The resource path also starts with a “/”, so after concatenation, there will be two consecutive “/”s in the URL. In this case, the server will return a 404 error.

I am not sure whether this is a Tornado Swirl bug or a Swagger Codegen bug. If you think this is a Swagger Codegen bug, I can submit an issue there.

**Comment by rnduldulaojr** [comment]
Removed the trailing slash in 0.1.20
